import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@fontsource/roboto";


const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
} & React.HTMLAttributes<HTMLHtmlElement>;

export default function RootLayout({ children, ...props }: RootLayoutProps) {
  return (
    <html lang="en" {...props}>
      <body className={roboto.className}>

    
          {children}
       
      </body>
    </html>
  );
}
